Repository corona-warn-app/cwa-website, pull requests merged in 2021-07, with the labels that each got.

#1460 Add Estland to InterOp FAQ
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1465 Link to test portal
  src/data/global.json
  src/partials/header.html
  src/partials/page-index.html
Labels: mirrored-to-jira

#1444 Updates release 2.5
  gulpfile.js
  src/assets/documents/cwa-privacy-notice-2.4-de.pdf
  src/assets/documents/cwa-privacy-notice-2.4-en.pdf
  src/assets/documents/cwa-privacy-notice-2.4-tr.pdf
  src/assets/documents/cwa-privacy-notice-de.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-tr.pdf
  src/data/faq.json
  src/data/faq_de.json
  src/data/privacy.json
  src/data/privacy_de.json
Labels: Fix 2.5, mirrored-to-jira

#1490 fix ios stat screenshots
  src/assets/screenshots/2-5/de/ios/iPhone 11 Pro-statistics_doses.png
  src/assets/screenshots/2-5/de/ios/iPhone 11 Pro-statistics_fully_vaccinated.png
  src/assets/screenshots/2-5/en/ios/iPhone 11 Pro-statistics_doses.png
  src/assets/screenshots/2-5/en/ios/iPhone 11 Pro-statistics_fully_vaccinated.png
Labels: Fix 2.5, mirrored-to-jira

#1489 Fix typo verschidenen in screenshots_de
  src/data/screenshots_de.json
Labels: Fix 2.5

#1482 Add information reg. 3rd party apps to FAQ (Addresses #1461)
  src/data/faq.json
  src/data/faq_de.json
Labels: Fix 2.5

#1493 Instructions for running cypress under Windows (closes #610)
  README.md
Labels: community

#1456 Test updates event registration
  .gitignore
  .vscode/settings.json
  README.md
  cypress/fixtures/selectors/sel.json
  cypress/integration/pages/eventRegistration.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: in review, mirrored-to-jira

#1504 FAQ: add fig schnelltestportal
  src/assets/img/faq/schnelltestportal_1.jpeg
  src/data/faq.json
  src/data/faq_de.json
Labels: Fix 2.5, mirrored-to-jira

#1515 fixed-EventRegistrationTest-i18n-Issue
  .gitignore
  README.md
  cypress/fixtures/copy/stringDe.json
  cypress/fixtures/copy/stringEn.json
  cypress/integration/pages/eventRegistration.js
Labels: mirrored-to-jira

#1528 FAQ EU_DCC_Validity
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1537 Science Blog 1 - EN version
  science/2021-06-15-science-blog-1/index.md
Labels: mirrored-to-jira

#1538 Update science.json - Intro EN
  src/data/science.json
Labels: mirrored-to-jira

#1523 Privacy notice and FAQ - release 2.6
  gulpfile.js
  src/assets/documents/cwa-privacy-notice-2.5-de.pdf
  src/assets/documents/cwa-privacy-notice-2.5-en.pdf
  src/assets/documents/cwa-privacy-notice-2.5-tr.pdf
  src/assets/documents/cwa-privacy-notice-de.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-tr.pdf
  src/data/faq.json
  src/data/faq_de.json
  src/data/privacy.json
  src/data/privacy_de.json
Labels: Fix 2.6, do-not-merge, mirrored-to-jira
