Repository corona-warn-app/cwa-website, pull requests merged in 2021-05, with the labels that each got.

#1183 FAQ RAT
  gulpfile.js
  src/assets/documents/cwa-privacy-notice-2.0-de.pdf
  src/assets/documents/cwa-privacy-notice-2.0-en.pdf
  src/assets/documents/cwa-privacy-notice-2.0-tr.pdf
  src/assets/documents/cwa-privacy-notice-de.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-tr.pdf
  src/data/faq.json
  src/data/faq_de.json
  src/data/privacy.json
  src/data/privacy_de.json
Labels: Fix 2.1, do-not-merge

#1186 FAQ and screenshots fix
  src/assets/img/screenshots/de/ios/rat_9.png
  src/assets/img/screenshots/en/ios/rat_6.png
  src/data/faq_de.json
  src/data/privacy_de.json
  src/data/screenshots.json
  src/data/screenshots_de.json
Labels: Fix 2.1

#1194 align text to the text used in both apps (closes 1193)
  src/data/eventregistration_de.json
Labels: do-not-merge

#1248 FAQ Lithuania
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1229 Skip Deploy Website workflow from running on forks
  .github/workflows/deploy-master.yml
Labels: mirrored-to-jira

#1237 Fix imperative form of 'lesen'
  src/data/index_de.json
Labels: confirmed

#1240 FAQ RAT new entries
  src/data/faq.json
  src/data/faq_de.json
Labels: Fix 2.2, mirrored-to-jira

#1235 release 2.2 updates
  gulpfile.js
  src/assets/documents/cwa-privacy-notice-2.1-de.pdf
  src/assets/documents/cwa-privacy-notice-2.1-en.pdf
  src/assets/documents/cwa-privacy-notice-2.1-tr.pdf
  src/assets/documents/cwa-privacy-notice-de.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-tr.pdf
  src/data/privacy.json
  src/data/privacy_de.json
Labels: Fix 2.2, mirrored-to-jira

#1243 FAQ error report
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1211 Add incompatibility_warning FAQ
  src/data/faq.json
  src/data/faq_de.json
Labels: Fix 2.2, mirrored-to-jira

#1292 Update cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
Labels: Fixed
