Repository corona-warn-app/cwa-website, pull requests merged in 2021-08, with the labels that each got.

#1570 Science Blog 3 DE
  science/2021-08-02-science-blog-3/fig_01.png
  science/2021-08-02-science-blog-3/fig_02.png
  science/2021-08-02-science-blog-3/fig_03.png
  science/2021-08-02-science-blog-3/fig_04.png
  science/2021-08-02-science-blog-3/fig_05.png
  science/2021-08-02-science-blog-3/fig_06.png
  science/2021-08-02-science-blog-3/fig_07.png
  science/2021-08-02-science-blog-3/fig_08.png
  science/2021-08-02-science-blog-3/index.md
  science/2021-08-02-science-blog-3/index_de.md
  science/2021-08-02-science-blog-3/tab_01.png
  science/2021-08-02-science-blog-3/tab_02.png
  science/2021-08-02-science-blog-3/tab_03.png
  science/2021-08-02-science-blog-3/tab_04.png
  science/2021-08-02-science-blog-3/tab_05.png
  science/2021-08-02-science-blog-3/tab_06.png
  science/2021-08-02-science-blog-3/tab_07.png
  science/2021-08-02-science-blog-3/tab_08.png
  science/2021-08-02-science-blog-3/tab_14.png
  science/2021-08-02-science-blog-3/tab_16.png
  src/assets/js/science.js
Labels: mirrored-to-jira

#1577 fix scienceblog (add tab 11+12)
  science/2021-08-02-science-blog-3/index_de.md
Labels: mirrored-to-jira

#1578 WebPage Create QR code: mention CLI
  src/data/eventregistration.json
  src/data/eventregistration_de.json
  src/partials/page-eventregistration.html
Labels: mirrored-to-jira

#1580 blog statistics tiles
  blog/2021-08-05-explain-statistics-tiles/7-day-incidence.png
  blog/2021-08-05-explain-statistics-tiles/7-day-r-value.png
  blog/2021-08-05-explain-statistics-tiles/7-tage-inzidenz.png
  blog/2021-08-05-explain-statistics-tiles/7-tage-r-wert.png
  blog/2021-08-05-explain-statistics-tiles/bestätigte-neuinfektionen.png
  blog/2021-08-05-explain-statistics-tiles/confirmed-new-infections.png
  blog/2021-08-05-explain-statistics-tiles/index.md
  blog/2021-08-05-explain-statistics-tiles/index_de.md
  blog/2021-08-05-explain-statistics-tiles/warnende-personen.png
  blog/2021-08-05-explain-statistics-tiles/warnings-by-app-users.png
Labels: mirrored-to-jira

#1599 Update FAQ article vac_cert_privileges_travel
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1600 Add FAQ article vac_cert_mismatch
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1612 Add a new content section for implementing test partners
  src/assets/img/rat-partner-option-1.png
  src/assets/img/rat-partner-option-1_en.png
  src/assets/img/rat-partner-option-2.png
  src/assets/img/rat-partner-option-2_en.png
  src/data/index.json
  src/data/index_de.json
  src/data/rat-partner.json
  src/data/rat-partner_de.json
  src/pages/de/rat-partner/index.html
  src/pages/en/rat-partner/index.html
  src/partials/page-rat-partner.html
Labels: enhancement, mirrored-to-jira

#1614 FAQ where_can_i_get_tested - fix float images
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1615 Add FAQ article hc_signature_invalid
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira, Fix 2.7

#1624 Fix FAQ eu_dcc_validity
  src/data/faq.json
  src/data/faq_de.json
Labels: bug

#1554 Privacy notice 2.7
  gulpfile.js
  src/assets/documents/cwa-privacy-notice-2.6-de.pdf
  src/assets/documents/cwa-privacy-notice-2.6-en.pdf
  src/assets/documents/cwa-privacy-notice-2.6-tr.pdf
  src/assets/documents/cwa-privacy-notice-de.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-tr.pdf
  src/data/privacy.json
  src/data/privacy_de.json
Labels: mirrored-to-jira, Fix 2.7

#1639 FAQ - where can I get tested: responsive images and two columns
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1641 Add new page for QR code creation instructions
  src/assets/documents/generateEventQRCodes.bat
  src/assets/documents/setupEventQRCodeGenerator.bat
  src/assets/documents/tables.csv
  src/assets/img/event-qr-code-guide/cmd-cwa-convert-confirmation.png
  src/assets/img/event-qr-code-guide/cmd-cwa-convert-csv.png
  src/assets/img/event-qr-code-guide/cmd-cwa-tool-confirmation.png
  src/assets/img/event-qr-code-guide/cmd-first-start.png
  src/assets/img/event-qr-code-guide/cmd-install-cwa-tool.png
  src/assets/img/event-qr-code-guide/excel.png
  src/assets/img/event-qr-code-guide/folder-event-qr-codes.png
  src/assets/img/event-qr-code-guide/folder-results.png
  src/assets/img/event-qr-code-guide/nodejs-setup.png
  src/assets/img/event-qr-code-guide/nodejs-setup2.png
  src/assets/img/event-qr-code-guide/nodejs-website.png
  src/assets/img/event-qr-code-guide/taskbar-search.png
  src/assets/img/event-qr-code-guide/taskbar.png
  src/data/event-qr-code-guide.json
  src/data/event-qr-code-guide_de.json
  src/data/eventregistration.json
  src/data/eventregistration_de.json
  src/pages/de/event-qr-code-guide/index.html
  src/pages/en/event-qr-code-guide/index.html
  src/partials/page-event-qr-code-guide.html
Labels: enhancement, mirrored-to-jira

#1656 Fix `ios_rat` anchors being used for Android screenshots
  src/data/screenshots-archive-2-2.json
  src/data/screenshots-archive-2-3.json
  src/data/screenshots-archive-2-4.json
  src/data/screenshots-archive-2-5.json
  src/data/screenshots-archive-2-6.json
  src/data/screenshots-archive.json
  src/data/screenshots.json
Labels: bug

#1687 Update Privacy notice 2.9 - (there was no privacy notice update 2.8)
  src/assets/documents/cwa-privacy-notice-2.7-de.pdf
  src/assets/documents/cwa-privacy-notice-2.7-en.pdf
  src/assets/documents/cwa-privacy-notice-2.7-tr.pdf
  src/assets/documents/cwa-privacy-notice-de.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-tr.pdf
  src/data/privacy.json
  src/data/privacy_de.json
Labels: mirrored-to-jira, Fix 2.9
