Repository corona-warn-app/cwa-website, pull requests merged in 2021-04, with the labels that each got.

#1089 Update FAQ, mention gateway Switzerland
  src/data/faq.json
  src/data/faq_de.json
Labels: documentation

#1087 Update privacy notice on coronawarn.app for version 2.0
  gulpfile.js
  src/assets/documents/cwa-privacy-notice-1.15-de.pdf
  src/assets/documents/cwa-privacy-notice-1.15-en.pdf
  src/assets/documents/cwa-privacy-notice-1.15-tr.pdf
  src/assets/documents/cwa-privacy-notice-de.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-tr.pdf
  src/data/privacy.json
  src/data/privacy_de.json
Labels: Fix 2.0

#1111 FAQ event registration
  src/assets/img/faq/evreg-tam-block.png
  src/data/faq.json
  src/data/faq_de.json
Labels: Fix 2.0

#1068 Android clear data function effects on Random IDs (closes #1067)
  src/data/faq.json
  src/data/faq_de.json
Labels: documentation, mirrored-to-jira

#1169 Remove "other" from QR-Code generator
  src/data/eventregistration.json
  src/data/eventregistration_de.json
Labels: confirmed

#1175 FAQ google_security_vulnerability
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira
