Repository corona-warn-app/cwa-website, pull requests merged in 2021-03, with the labels that each got.

#924 Update privacy notice on coronawarn.app for version 1.13
  gulpfile.js
  src/assets/documents/cwa-privacy-notice-1.12-de.pdf
  src/assets/documents/cwa-privacy-notice-1.12-en.pdf
  src/assets/documents/cwa-privacy-notice-1.12-tr.pdf
  src/assets/documents/cwa-privacy-notice-de.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-tr.pdf
  src/data/privacy.json
  src/data/privacy_de.json
Labels: documentation, mirrored-to-jira

#989 FAQ - update "recovered"
  src/data/faq.json
  src/data/faq_de.json
Labels: documentation

#997 5703 lazyloading
  src/assets/js/lazyload.js
  src/partials/page-screenshots.html
Labels: documentation, enhancement

#1016 Update privacy notice on coronawarn.app for version 1.15
  gulpfile.js
  src/assets/documents/cwa-privacy-notice-1.13-de.pdf
  src/assets/documents/cwa-privacy-notice-1.13-en.pdf
  src/assets/documents/cwa-privacy-notice-1.13-tr.pdf
  src/assets/documents/cwa-privacy-notice-de.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-tr.pdf
  src/data/privacy.json
  src/data/privacy_de.json
Labels: mirrored-to-jira
