Repository corona-warn-app/cwa-website, pull requests merged in 2021-09, with the labels that each got.

#1694 Update FAQ vac_cert_red_warning
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1699 Event multi QR code generator
  THIRD-PARTY-NOTICES
  package-lock.json
  package.json
  src/assets/img/pt-poster-1.0.0-multiqr.png
  src/assets/js/eventregistration.js
  src/data/eventregistration.json
  src/data/eventregistration_de.json
  src/partials/page-eventregistration.html
Labels: enhancement, mirrored-to-jira

#1711 Fix/8884 invalid certificates Android 2.8
  src/data/screenshots.json
  src/data/screenshots_de.json
Labels: mirrored-to-jira, community

#1715 Blog 2.9
  blog/2021-08-25-CWA-2-9/booster-impfung.png
  blog/2021-08-25-CWA-2-9/booster-impfung_v2.png
  blog/2021-08-25-CWA-2-9/booster-impfung_v2_en.png
  blog/2021-08-25-CWA-2-9/iPhone 11 Pro-onbehalfwarning_date_time_selection.png
  blog/2021-08-25-CWA-2-9/iPhone 11 Pro-onbehalfwarning_date_time_selection_en.png
  blog/2021-08-25-CWA-2-9/iPhone 11 Pro-onbehalfwarning_info_0002.png
  blog/2021-08-25-CWA-2-9/iPhone 11 Pro-onbehalfwarning_info_0002_en.png
  blog/2021-08-25-CWA-2-9/iPhone 11 Pro-onbehalfwarning_location_selection.png
  blog/2021-08-25-CWA-2-9/iPhone 11 Pro-onbehalfwarning_location_selection_en.png
  blog/2021-08-25-CWA-2-9/iPhone 11 Pro-onbehalfwarning_tan.png
  blog/2021-08-25-CWA-2-9/iPhone 11 Pro-onbehalfwarning_tan_en.png
  blog/2021-08-25-CWA-2-9/index.md
  blog/2021-08-25-CWA-2-9/index_de.md
  blog/2021-08-25-CWA-2-9/my_qr_codes.png
  blog/2021-08-25-CWA-2-9/test-certificate-en.png
  blog/2021-08-25-CWA-2-9/testzertifikat-de.png
  blog/2021-08-25-CWA-2-9/warn_for_others_scan.png
  blog/2021-08-25-CWA-2-9/warnen(1).png
  blog/2021-08-25-CWA-2-9/warnen(2).png
  blog/2021-08-25-CWA-2-9/warnen(3).png
  blog/2021-08-25-CWA-2-9/warnen(4).png
  blog/2021-08-25-CWA-2-9/warnen(5).png
  blog/2021-08-25-CWA-2-9/warnen-qr-code.png
  src/assets/documents/cwa-privacy-notice-2.7-de.pdf
  src/assets/documents/cwa-privacy-notice-2.7-en.pdf
  src/assets/documents/cwa-privacy-notice-2.7-tr.pdf
  src/assets/documents/cwa-privacy-notice-de.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-tr.pdf
  src/data/privacy.json
  src/data/privacy_de.json
Labels: Fix 2.9

#1683 Add new FAQ entry clarifying dcc validity check change in CWA version 2.8 (Addresses #1682)
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1721 Update FAQ vac_cert_mismatch
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1736 Add eu_dcc_export + vac_cert_booster
  src/data/faq.json
  src/data/faq_de.json
Labels: Fix 2.10

#1745 Science blog 3 DE updates
  science/2021-08-02-science-blog-3/fig_01.png
  science/2021-08-02-science-blog-3/fig_02.png
  science/2021-08-02-science-blog-3/fig_03.png
  science/2021-08-02-science-blog-3/fig_04.png
  science/2021-08-02-science-blog-3/fig_05.png
  science/2021-08-02-science-blog-3/fig_06.png
  science/2021-08-02-science-blog-3/fig_07.png
  science/2021-08-02-science-blog-3/fig_08.png
  science/2021-08-02-science-blog-3/fig_10.png
  science/2021-08-02-science-blog-3/fig_11.png
  science/2021-08-02-science-blog-3/fig_13.png
  science/2021-08-02-science-blog-3/fig_14.png
  science/2021-08-02-science-blog-3/fig_16.png
  science/2021-08-02-science-blog-3/fig_17.png
  science/2021-08-02-science-blog-3/index_de.md
  science/2021-08-02-science-blog-3/tab_01.png
  science/2021-08-02-science-blog-3/tab_02.png
  science/2021-08-02-science-blog-3/tab_03.png
  science/2021-08-02-science-blog-3/tab_04.png
  science/2021-08-02-science-blog-3/tab_05.png
  science/2021-08-02-science-blog-3/tab_06.png
  science/2021-08-02-science-blog-3/tab_07.png
  science/2021-08-02-science-blog-3/tab_08.png
  science/2021-08-02-science-blog-3/tab_11.png
  science/2021-08-02-science-blog-3/tab_14.png
  science/2021-08-02-science-blog-3/tab_15.png
  science/2021-08-02-science-blog-3/tab_16.png
  science/2021-08-02-science-blog-3/tab_19.png
  science/2021-08-02-science-blog-3/tab_23.png
  science/2021-08-02-science-blog-3/tab_24.png
  science/2021-08-02-science-blog-3/tab_25.png
  src/services/science-blog-processor.js
Labels: enhancement, mirrored-to-jira
