Repository corona-warn-app/cwa-website, pull requests merged in 2021-02, with the labels that each got.

#838 Change EULA link (German -> English) (EXPOSUREAPP-4985)
  src/data/index.json
Labels: mirrored-to-jira

#847 Update privacy notice on coronawarn.app for version 1.12 [EXPOSUREAPP-4734]
  gulpfile.js
  src/assets/documents/cwa-privacy-notice-1.10-de.pdf
  src/assets/documents/cwa-privacy-notice-1.10-en.pdf
  src/assets/documents/cwa-privacy-notice-1.10-tr.pdf
  src/assets/documents/cwa-privacy-notice-de.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-tr.pdf
  src/data/privacy.json
  src/data/privacy_de.json
Labels: Fix 1.12, mirrored-to-jira

#858 Update website - Section: This is how the app works best
  src/data/index.json
  src/data/index_de.json
Labels: Fix 1.12

#852 [WIP] Update FAQ: Min system requirements
  src/data/faq.json
  src/data/faq_de.json
Labels: Fix 1.12

#857 Update FAQ ios135
  src/data/faq.json
  src/data/faq_de.json
Labels: Fix 1.12

#853 Shorten title for FAQ link text preventing text overflow out of box (closes #849)
  src/data/index_de.json
Labels: Fix 1.12
