Repository corona-warn-app/cwa-website, pull requests merged in 2021-06, with the labels that each got.

#1210 Blog: Whitespace below footer in blogentries
  src/assets/scss/_blog.scss
Labels: mirrored-to-jira

#1324 Imprint/Legal notice: SAP -> RKI
  src/data/imprint.json
  src/data/imprint_de.json
Labels: documentation, mirrored-to-jira

#1326 fix href and '
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1332 Align all `page-title`s & improve `page-description` s (Closes #1331)
  src/pages/de/blog/archiv/index.html
  src/pages/de/blog/index.html
  src/pages/de/community/index.html
  src/pages/de/eventregistration/index.html
  src/pages/de/faq/index.html
  src/pages/de/imprint/index.html
  src/pages/de/index.html
  src/pages/de/news/index.html
  src/pages/de/privacy/index.html
  src/pages/de/terms-of-use/index.html
  src/pages/en/blog/archive/index.html
  src/pages/en/blog/index.html
  src/pages/en/community/index.html
  src/pages/en/faq/index.html
  src/pages/en/imprint/index.html
  src/pages/en/index.html
  src/pages/en/news/index.html
  src/pages/en/privacy/index.html
  src/pages/en/screenshots-archive/2-2.html
  src/pages/en/screenshots/index.html
  src/pages/en/terms-of-use/index.html
  src/pages/index.html
Labels: Fix 2.3, do-not-merge

#1328 Release 2.3 privacy notice
  gulpfile.js
  src/assets/documents/cwa-privacy-notice-2.2-de.pdf
  src/assets/documents/cwa-privacy-notice-2.2-en.pdf
  src/assets/documents/cwa-privacy-notice-2.2-tr.pdf
  src/assets/documents/cwa-privacy-notice-de.pdf
  src/assets/documents/cwa-privacy-notice-en.pdf
  src/assets/documents/cwa-privacy-notice-tr.pdf
  src/data/privacy.json
  src/data/privacy_de.json
Labels: Fix 2.3, mirrored-to-jira

#1313 FAQ vaccination
  src/data/faq.json
  src/data/faq_de.json
Labels: documentation, mirrored-to-jira

#1389 Science blog graphs
  science/2021-06-15-science-blog-1/index_de.md
Labels: do-not-merge

#1418 FAQ on the rec certificate
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#1443 update FAQ ios_black_screen
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira
