Repository corona-warn-app/cwa-website, pull requests merged in 2022-12, with the labels that each got.

#3263 Remove extra span end tag from faq breadcrumbs
  src/partials/page-faq-results.html
Labels: bug

#3256 Change video alt to aria-label in science and sign-language
  science/2021-06-15-science-blog-1/index.md
  science/2021-06-15-science-blog-1/index_de.md
  src/data/sign-language_de.json
Labels: bug

#3271 Remove role="main" from layout files
  src/layouts/blog.html
  src/layouts/default.html
  src/layouts/error-pages.html
  src/layouts/science.html
Labels: bug

#3270 Update WRITE_BLOG_POSTS.md for images
  docs/WRITE_BLOG_POSTS.md
Labels: documentation

#3260 Faq backup update
  src/data/faq.json
  src/data/faq_de.json
Labels: enhancement, faq

#3220 Update traffic_monitoring
  src/data/faq.json
  src/data/faq_de.json
Labels: enhancement, faq

#3274 Reformat faq json source
  src/data/faq.json
  src/data/faq_de.json
Labels: faq

#3288 Change Cypress baseURL to https://www.coronawarn.app
  .github/workflows/cypress-test-prod.yml
  README.md
  cypress/e2e/mime.cy.js
Labels: mirrored-to-jira

#3292 Remove obsolete FAQ information about Prioritized Background Activity
  src/data/faq.json
  src/data/faq_de.json
Labels: mirrored-to-jira

#3296 Npm full update
  package-lock.json
  package.json
  src/assets/scss/_functions.scss
Labels: dependencies, mirrored-to-jira, technical-issue
